version: '3.8'

services:
  backend:
    image: donations-tracker-backend:${TAG}
    build: ./backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ATLAS_CONNECTION: ${ATLAS_CONNECTION}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      PORT: ${BACKEND_DOCKER_PORT}
    ports:
      - ${BACKEND_LOCAL_PORT}:${BACKEND_DOCKER_PORT}
    container_name: donations-tracker-backend
    networks:
      - tracker
    depends_on:
      - db
  frontend:
    image: donations-tracker-frontend:${TAG}
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
        - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    environment:
      NODE_ENV: production
    ports:
      - ${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}
    container_name: donations-tracker-frontend
    networks:
      - tracker
  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: donations-tracker-db
    networks:
      - tracker
    volumes:
      - mongo-data:/data/db
networks:
  tracker:
    driver: bridge
volumes:
  mongo-data:
    driver: local