version: '3.8'

services:
  backend:
    image: donations-tracker-backend:latest
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: donations-tracker-backend
    environment:
      CONNECTION_STRING: mongodb://donations-tracker-db:27017/dev
      CLIENT_ORIGIN: http://localhost:8080
      SESSION_SECRET: top secret
      PORT: 8081
      DEBUG: backend:*
    ports:
      - 8081:8081
    networks:
      - tracker
    volumes:
      - "/backend/node_modules/"
      - "./backend:/backend"
    depends_on:
      - db
  frontend:
    image: donations-tracker-frontend:latest
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
      args:
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
        VITE_GOOGLE_MAP_ID: ${VITE_GOOGLE_MAP_ID}
        VITE_API_URL: ${VITE_API_URL}
    container_name: donations-tracker-frontend
    environment:
      PORT: 8080
      WDS_SOCKET_HOST: 127.0.0.1 
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - 8080:8080
    networks:
      - tracker
    volumes:
      - "/app/node_modules/"
      - "./frontend:/app"
    depends_on:
      - backend
  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: donations-tracker-db
    networks:
      - tracker
    volumes:
      - mongo-data:/data/db
networks:
  tracker:
    driver: bridge
volumes:
  mongo-data:
    driver: local