version: '3.8'

services:
  backend:
    image: donations-tracker-backend:${TAG}
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: donations-tracker-backend
    environment:
      NODE_ENV: production
      CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      PORT: 8081
      DEBUG: backend:*
    ports:
      - 8081:8081
    networks:
      - tracker
    depends_on:
      - db
  frontend:
    image: donations-tracker-frontend:${TAG}
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: donations-tracker-frontend
    environment:
      PORT: 8080
      WDS_SOCKET_HOST: 127.0.0.1 
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
    ports:
      - 8080:8080
    networks:
      - tracker
    volumes:
      - "./frontend:/app"
    depends_on:
      - backend
  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: donations-tracker-db
    networks:
      - tracker
    volumes:
      - mongo-data:/data/db
networks:
  tracker:
    driver: bridge
volumes:
  mongo-data:
    driver: local