version: '3.4'

services:
  backend:
    image: donations-tracker-backend:${TAG}
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      ATLAS_CONNECTION: ${ATLAS_CONNECTION}
    ports:
      - 8081:8081
  frontend:
    image: donations-tracker-frontend:${TAG}
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
    volumes:
      - ./frontend:/app
