version: '3.8'

services:
  backend:
    image: donations-tracker-backend:${TAG}
    build: ./backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ATLAS_CONNECTION: ${ATLAS_CONNECTION}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      PORT: ${BACKEND_DOCKER_PORT}
    ports:
      - ${BACKEND_LOCAL_PORT}:${BACKEND_DOCKER_PORT}
    networks:
      - tracker
  frontend:
    image: donations-tracker-frontend:${TAG}
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    environment:
      NODE_ENV: production
    ports:
      - ${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}
    networks:
      - tracker
networks:
  tracker: